### ISSUE TITLE
Mac OSX Mojave 10.14.5 - Saves are blocking

### ISSUE THREAD

**Issue by briser** [MicroPad/Web#167] opened 2019-07-22 15:54 UTC
When working on importing and reorganizing my notes/notebooks (the stacks/notebooks/notes hierarchy isn't preserved on import from evernote (making a seperate issue for this)) I found that if I did not let the auto save after moving or loading each note complete that I would run into issues with the app locking up and requiring a restart to recover. I'm not sure where to grab logs for this behavior but will try to record it and add a link to that here.

**Comment by NickGeek** [comment] 2019-07-23 06:08
Hey, that sounds serious. Could you please try in the web-version in Chrome (https://web.getmicropad.com) and with the [Redux Dev Tools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd) installed?

When the page loads, if you open your dev tools (Option+Cmd+I) and click on the "Redux Dev Tools" tab you will see a log of every action performed throughout the app and how it changed the state of the application.

**Comment by NickGeek** [comment] 2019-08-16 12:14
I've definitely ran into this issue before but I'm having lots of trouble replicating it on dev. I'm going to push in a fix of what I hope will fix it, but if you have a consistent way to reproduce, I'd love to hear it.

I'm going to put some code in for the next release to hopefully help with this but I won't find out until it's out there.

**Comment by NickGeek** [comment] 2019-09-29 02:51
I haven't ran into this issue since my potential fix went out so I'm closing it for now.

**Closed by NickGeek** 2019-09-29 02:51 UTC
Labels: bug
