### ISSUE TITLE
Feature request: Two possible enhancements

### ISSUE THREAD

**Issue by corypanshin** [MicroPad/Web#153] opened 2019-06-20 15:19 UTC
I'm already finding MicroPad useful, but I can see two areas for improvement.  One is that I don't see any way to change the order in which notes are listed within a section.  It looks like the newest one is always added at the bottom.  Being able to reorder them manually would be ideal, but if that is not possible, having them either alphabetical or with the most recently modified at the top would make it easier to navigate.

The other is that I would like it if I could roll up elements so that only the top line shows.  That would make it easier to take advantage of the non-linear, infinite whiteboard aspect of each note by scattering elements around and moving them into related groupings.  As it is, just one or two large elements hog a lot of screen space and prevent that sort of flexibility.

**Comment by NickGeek** [comment] 2019-06-21 08:25
Hey, thanks for the feedback! If possible could you please split this into two separate issues, because they might not be fixed at the same time.

Also, could you please expand on the second thing? I'm not quite sure I 100% get what you mean so a drawing or something would be super helpful :-)

**Comment by NickGeek** [comment] 2019-06-25 01:13
Thanks for splitting that! Closing this one as a duplicate of #155 and #154.

**Closed by NickGeek** 2019-06-25 01:13 UTC
